spec:
  structures:
  - content_blocks
  label: FAQ Section
  description: A FAQ section with a list of frequently asked questions.
  icon: 'help_outline'
  tags:
    - FAQ
    - Text
    - Questions

blueprint:
  title:
    title_text: 'Frequently Asked Questions'
    title_color: '#3dc3dc'
  faq_items:
    - question:
        type: 'text'
        label: 'Question Text'
      answer:
        type: 'markdown'
        label: 'Answer Text'

_inputs:
  title:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: title_text
          - 'Update FAQ section title.'
  faq_items:
    options:
      preview:
        icon: 'help_outline'
        text:
          - 'Question'
        subtext:
          - 'Update the question and answer pairs.'
    fields:
      - name: question
        type: text
        label: 'Question Text'
      - name: answer
        type: markdown
        label: 'Answer Text'


