# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: FAQ Section
  description: A FAQ section with a list of frequently asked questions.
  icon: 'help_outline'
  tags:
    - FAQ
    - Text
    - Questions

# Defines the structure of this component, as well as the default values
blueprint:
  title: Frequently Asked Questions
  faqs:
    - question: What is an Optometrist?
      answer: >-
        The Canadian Association of Optometrists (CAO) defines an optometrist, or Doctor of Optometry, 
        as an independent primary health care provider with expertise in examining, diagnosing, treating, 
        managing, and preventing diseases and disorders related to the visual system, the eyes, and their 
        associated structures. Additionally, optometrists are skilled in identifying ocular manifestations of systemic conditions.

# Overrides any fields in the blueprint when viewing this component in the component browser
_inputs:
  faqs:
    type: group
    label: FAQs
    options:
      preview:
        icon: 'help_outline'
    fields:
      - name: question
        type: text
        label: Question
      - name: answer
        type: markdown
        label: Answer
        options:
          allow_resize: true
          empty_type: 'null'
          initial_height: 200
          preview:
            icon: 'subject'
