# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: FAQ Section
  description: A FAQ section with a list of frequently asked questions.
  icon: 'help_outline'
  tags:
    - FAQ
    - Text
    - Questions

# Defines the structure of this component, as well as the default values
blueprint:
  faqtext:
    markdown_content: >-
      A starting point for developers looking to build a website with Astro, using Bookshop components in CloudCannon. Create your own copy, and start creating your own components to use in the CloudCannon CMS.
    color: '#393939'


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  faqtext:
    options:
      preview:
        icon: 'short_text'
        text:
          - Subheading
        subtext:
          - 'Update subheading content and color.'