# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Markdown Section
  description: A markdown section 
  icon: 'help_outline'
  tags:
    - Markdown
    - Text
    - Questions

# Defines the structure of this component, as well as the default values
blueprint:
  markdown:
    heading:
    markdown_content: >-
      A starting point for developers looking to build a website with Astro, using Bookshop components in CloudCannon. Create your own copy, and start creating your own components to use in the CloudCannon CMS.


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  markdown:
    options:
      preview:
        icon: 'short_text'
        text:
          - markdowns
        subtext:
          - 'Update frequently asked questions.'