spec:
  structures:
    - content_blocks
  label: Partners Alt Section
  description: Section displaying partner logos with links
  icon: 'business'
  tags:
    - Partners
    - Logos
    - Section

blueprint:
  topper: "Insurance & Billing"
  title: "Our Partners"
  subheading:
    markdown_content: "Supporting optometry through strong partnerships."
    color: "#000000"
  partners:
    - image: "@assets/Alberta-Collage-of-Optometrists.png"
      alt: "Partner 1"
      link: "#"
    - image: "@assets/aao-logo.png"
      alt: "Partner 2"
      link: "#"
    - image: "@assets/cao-logo.png"
      alt: "Partner 3"
      link: "#"
