# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Section
  description: A hero section with a background image, heading, subheading, image, and buttons.
  icon: 'cottage'
  tags:
    - Hero
    - Image
    - Text
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: 
      image_path: 
      type: 'image'
      alt_text: An Image
  heading:
    heading_text: Alberta's Premier Vision Care Provider
    heading_color: '#3dc3dc'
  subheading:
    markdown_content: >-
      Proudly serving Edmonton, Spruce Grove, St. Albert, and Sherwood Park with comprehensive eye exams and optometry services.
    color: '#393939'
  buttons: 
    - text:
        type: 'text'
        label: 'Button Text'
      link:
        type: 'url'
        label: 'Button Link'
      background_color:
        type: 'color'
        label: 'Button Background Color'
      hover_brightness:
        type: 'range'
        label: 'Hover Brightness'
        min: 0
        max: 100
      text_color:
        type: 'color'
        label: 'Button Text Color'
