spec:
  structures:
    - content_blocks
  label: Bookshop CTA Section
  description: Section with a call to action for a bookshop
  icon: 'book'
  tags:
    - CTA
    - Section
    - Bookshop

blueprint:
  title: Bookshop CTA Section
  fields:
    - label: Topper Text
      type: string
      default: 'Discover Your Next Read'
    - label: Title
      type: string
      default: 'Browse Our Bestsellers'
    - label: Button 1 Text
      type: string
      default: 'Shop Now'
    - label: Button 1 Link
      type: string
      default: '#shop-now'
    - label: Button 2 Text
      type: string
      default: 'Contact Us'
    - label: Button 2 Link
      type: string
      default: '#contact-us'
    - label: Medium Image URL
      type: string
      default: 'https://example.com/medium-book-image.jpg'
    - label: Large Image URL
      type: string
      default: 'https://example.com/large-book-image.jpg'
    - label: Image Alt Text
      type: string
      default: 'Books displayed on a shelf'

_inputs:
  fields:
    - label: Topper Text
      type: text
      placeholder: 'Enter the top text for the CTA section'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Topper Text'
          subtext:
            - 'Update the text displayed at the top of the section.'

    - label: Title
      type: text
      placeholder: 'Enter the main title for the CTA section'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Title'
          subtext:
            - 'Update the main title of the CTA section.'

    - label: Button 1 Text
      type: text
      placeholder: 'Enter text for the first button'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Button 1 Text'
          subtext:
            - 'Update the text for the primary action button.'

    - label: Button 1 Link
      type: text
      placeholder: 'Enter URL for the first button'
      options:
        preview:
          icon: 'link'
          text:
            - 'Button 1 Link'
          subtext:
            - 'Update the URL for the primary action button.'

    - label: Button 2 Text
      type: text
      placeholder: 'Enter text for the second button'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Button 2 Text'
          subtext:
            - 'Update the text for the secondary action button.'

    - label: Button 2 Link
      type: text
      placeholder: 'Enter URL for the second button'
      options:
        preview:
          icon: 'link'
          text:
            - 'Button 2 Link'
          subtext:
            - 'Update the URL for the secondary action button.'

    - label: Medium Image URL
      type: text
      placeholder: 'Enter URL for the medium-sized image'
      options:
        preview:
          icon: 'image'
          text:
            - 'Medium Image URL'
          subtext:
            - 'Update the URL for the image shown on small screens.'

    - label: Large Image URL
      type: text
      placeholder: 'Enter URL for the large image'
      options:
        preview:
          icon: 'image'
          text:
            - 'Large Image URL'
          subtext:
            - 'Update the URL for the image shown on larger screens.'

    - label: Image Alt Text
      type: text
      placeholder: 'Enter alt text for the image'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Image Alt Text'
          subtext:
            - 'Update the alt text for the image to improve accessibility.'
