spec:
  structures:
    - content_blocks
  label: Alberta Vision Care CTA Section
  description: Section with a call to action for Alberta Vision Care
  icon: 'visibility'
  tags:
    - CTA
    - Vision Care
    - Section

blueprint:
  title: Alberta Vision Care CTA Section
  fields:
    - label: Topper Text
      key: topper_text
      type: string
      default: 'Your Vision, Our Priority'
    - label: Title
      key: title
      type: string
      default: 'Explore Our Services'
    - label: Buttons
      key: buttons
      type: array
      structure:
        - label: Button Text
          key: text
          type: string
        - label: Button Link
          key: link
          type: string
    - label: Medium Image URL
      key: medium_image_url
      type: string
      default: 'https://example.com/vision-care-medium.jpg'
    - label: Large Image URL
      key: large_image_url
      type: string
      default: 'https://example.com/vision-care-large.jpg'
    - label: Image Alt Text
      key: image_alt_text
      type: string
      default: 'Vision care clinic with eye exam equipment'

_inputs:
  fields:
    - label: Topper Text
      key: topper_text
      type: text
      placeholder: 'Enter the top text for the CTA section'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Topper Text'
          subtext:
            - 'Update the text displayed at the top of the section.'

    - label: Title
      key: title
      type: text
      placeholder: 'Enter the main title for the CTA section'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Title'
          subtext:
            - 'Update the main title of the CTA section.'

    - label: Buttons
      key: buttons
      type: group
      structure:
        - label: Button Text
          key: text
          type: text
          placeholder: 'Enter text for the button'
          options:
            preview:
              icon: 'short_text'
              text:
                - 'Button Text'
              subtext:
                - 'Update the text for this button.'
        - label: Button Link
          key: link
          type: text
          placeholder: 'Enter URL for the button'
          options:
            preview:
              icon: 'link'
              text:
                - 'Button Link'
              subtext:
                - 'Update the URL for this button.'

    - label: Medium Image URL
      key: medium_image_url
      type: text
      placeholder: 'Enter URL for the medium-sized image'
      options:
        preview:
          icon: 'image'
          text:
            - 'Medium Image URL'
          subtext:
            - 'Update the URL for the image shown on small screens.'

    - label: Large Image URL
      key: large_image_url
      type: text
      placeholder: 'Enter URL for the large image'
      options:
        preview:
          icon: 'image'
          text:
            - 'Large Image URL'
          subtext:
            - 'Update the URL for the image shown on larger screens.'

    - label: Image Alt Text
      key: image_alt_text
      type: text
      placeholder: 'Enter alt text for the image'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Image Alt Text'
          subtext:
            - 'Update the alt text for the image to improve accessibility.'
