# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Alberta Vision Care CTA Section
  description: Section with a call to action for Alberta Vision Care
  icon: 'visibility'
  tags:
    - CTA
    - Vision Care
    - Section

# Defines the structure of this component, as well as the default values
blueprint:
  title: Alberta Vision Care CTA Section
  fields:
    - type: string
      label: Topper Text
      key: topper_text
      default: 'Your Vision, Our Priority'
      
    - type: string
      label: Title
      key: title
      default: 'Explore Our Services'
      
    # - type: array
    #   label: Buttons
    #   key: buttons
    #   structure:
    #     - type: string
    #       label: Button Text
    #       key: text
    #       default: 'Click Here'
    #     - type: string
    #       label: Button Link
    #       key: link
    #       default: 'https://example.com'
      
    - type: string
      label: Medium Image URL
      key: medium_image_url
      default: 'https://example.com/vision-care-medium.jpg'
      
    - type: string
      label: Large Image URL
      key: large_image_url
      default: 'https://example.com/vision-care-large.jpg'
      
    - type: string
      label: Image Alt Text
      key: image_alt_text
      default: 'Vision care clinic with eye exam equipment'

# Overrides any fields in the blueprint when viewing this component in the component browser
_inputs:
  fields:
    - type: text
      label: Topper Text
      key: topper_text
      placeholder: 'Enter the top text for the CTA section'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Topper Text'
          subtext:
            - 'Update the text displayed at the top of the section.'

    - type: text
      label: Title
      key: title
      placeholder: 'Enter the main title for the CTA section'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Title'
          subtext:
            - 'Update the main title of the CTA section.'

    # - type: array
    #   label: Buttons
    #   key: buttons
    #   structure:
    #     - type: text
    #       label: Button Text
    #       key: text
    #       placeholder: 'Enter text for the button'
    #       options:
    #         preview:
    #           icon: 'short_text'
    #           text:
    #             - 'Button Text'
    #           subtext:
    #             - 'Update the text for this button.'
        - type: text
          label: Button Link
          key: link
          placeholder: 'Enter URL for the button'
          options:
            preview:
              icon: 'link'
              text:
                - 'Button Link'
              subtext:
                - 'Update the URL for this button.'

    - type: text
      label: Medium Image URL
      key: medium_image_url
      placeholder: 'Enter URL for the medium-sized image'
      options:
        preview:
          icon: 'image'
          text:
            - 'Medium Image URL'
          subtext:
            - 'Update the URL for the image shown on small screens.'

    - type: text
      label: Large Image URL
      key: large_image_url
      placeholder: 'Enter URL for the large image'
      options:
        preview:
          icon: 'image'
          text:
            - 'Large Image URL'
          subtext:
            - 'Update the URL for the image shown on larger screens.'

    - type: text
      label: Image Alt Text
      key: image_alt_text
      placeholder: 'Enter alt text for the image'
      options:
        preview:
          icon: 'short_text'
          text:
            - 'Image Alt Text'
          subtext:
            - 'Update the alt text for the image to improve accessibility.'
