# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Meet The Team
  description: A section showcasing team members with their roles and social links.
  icon: 'group'
  tags:
    - Team
    - Profile

# Defines the structure of this component, as well as the default values
blueprint:
  title: Our Expert Team
  topper: Meet Our Team
  description: >-
    Meet our dedicated team of professionals who are passionate about what they do.
  team_members:
    - name: Doctor Gill
      job_title: Doctor
      description: Dr. Gill, originally from the Philippines, moved to Edmonton with her family at the age of six. She pursued her undergraduate studies at the University of Saskatchewan...
      image: https://ik.imagekit.io/boxhuwbys/Alberta-Vision-Care-DrGill.webp
      read_more_url: /team-members/doctor-gill/
    - name: 
      job_title: 
      description: 
      image: https://ik.imagekit.io/boxhuwbys/alberta-vision-care-DrEaswaran.webp?updatedAt=1724910341474
      read_more_url: /team-members/doctor-gill/

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
    options:
      preview:
        icon: 'short_text'
  topper:
    type: text
    label: Topper
    options:
      preview:
        icon: 'short_text'
  description:
    type: textarea
    label: Description
    options:
      preview:
        icon: 'subject'
  team_members:
    type: group
    label: Team Members
    options:
      preview:
        icon: 'person'
    fields:
      - name: name
        type: text
        label: Name
      - name: job_title
        type: text
        label: Job Title
      - name: description
        type: textarea
        label: Description
      - name: image
        type: group
        label: Images
        fields:
          - name: mobile
            type: image
            label: Mobile Image
          - name: tablet
            type: image
            label: Tablet & Above Image
      - name: read_more_url
        type: url
        label: Read More URL
