# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Locations
  description: A section with a map and various locations.
  icon: 'map'
  tags:
    - Map
    - Section

# Defines the structure of this component, as well as the default values
blueprint:
  title: Locations
  map_iframe_src: "https://www.google.com/maps/d/embed?mid=1Rhxpvbfsh0ZWprSjaMlTOi3zsbpH0zQ&ehbc=2E312F"
  locations:
    - id: 1
      name: 17th Street
      address: 4410-17th St. N.W.
      number: 780-450-8328
      numberLink: tel:7804508328
      ext: 135
      mapLink: ""
    - id: 2
      name: South Common
      address: 9711-23rd Ave. N.W.
      number: 780 490 3949
      numberLink: tel:780 490 3949
      ext: ""
      mapLink: ""
    - id: 3
      name: Windermere
      address: 1155 Windermere Way SE
      number: 780 438 9235
      numberLink: tel:780 438 9235
      ext: 137
      mapLink: ""
    - id: 4
      name: Heritage Valley
      address: 11839 26 Ave SW
      number: 780-438-3303
      numberLink: tel:780-438-3303
      ext: 135
      mapLink: ""
    - id: 5
      name: Calgary Trail
      address: 4821 Calgary Trail N.W.
      number: 780-430-2797
      numberLink: tel:780-430-2797
      ext: 135
      mapLink: ""
    - id: 6
      name: Castledowns
      address: 12350 – 137 Ave. NW.
      number: 780-406-3787
      numberLink: tel:780-406-3787
      ext: ""
      mapLink: ""
    - id: 7
      name: Stony Plain Road
      address: 17303 Stony Plain Road NW.
      number: 780-486-8469
      numberLink: tel:780-486-8469
      ext: ""
      mapLink: ""
    - id: 8
      name: Clairview
      address: 4950-137 Ave. N.W.
      number: 780-472-4727
      numberLink: tel: 780-472-4727
      ext: 135
      mapLink: ""
    - id: 9
      name: Sherwood Park
      address: 100-410 Baseline Road
      number: 780-417-5212
      numberLink: tel:780-417-5212
      ext: ""
      mapLink: ""
    - id: 10
      name: St. Albert
      address: 101 St. Albert Road
      number: 780-418-6847
      numberLink: tel: 780-418-6847
      ext: ""
      mapLink: ""
    - id: 11
      name: Spruce Grove
      address: #10 – 110 Campsite Road
      number: 780-960-7427
      numberLink: tel:780-960-7427
      ext: ""
      mapLink: ""
    - id: 12
      name: Kingsway
      address: 11541 Kingsway Avenue
      number: 780-733-1400
      numberLink: tel:780-733-1400
      ext: 351
      mapLink: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  # Here you can set preview-specific configurations if needed

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
    options:
      preview:
        icon: 'short_text'
  map_iframe_src:
    type: text
    label: Map Iframe Source
    options:
      preview:
        icon: 'map'
  locations:
    type: group
    label: Locations
    options:
      preview:
        icon: 'location_on'
    fields:
      - name: id
        type: number
        label: ID
      - name: name
        type: text
        label: Location Name
      - name: address
        type: text
        label: Address
      - name: number
        type: text
        label: Phone Number
      - name: numberLink
        type: text
        label: Phone Number Link
      - name: ext
        type: text
        label: Extension
      - name: mapLink
        type: text
        label: Map Link
