spec:
  structures:
    - content_blocks
  label: Page Banner
  description: Page Banner with Background Image & Breadcrumbs
  icon: 'image'
  tags:
  - Banner
  - Section

blueprint:
  title: "About Us"
  breadcrumbs:
    - label: "Home"
      url: "/"
      active: false
    - label: "About Us"
      url: "/about-us"
      active: true
  backgroundImage:
    mobile:
    desktop: